name: svisionenv
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
    - numpy==1.16.4
    - scipy==1.5.4
    - opencv-python-headless
    - beautifulsoup4
    - intervaltree
    - pyvcf
    - tensorflow==1.14.0
    - pysam