name: svisionenv
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - tensorflow=1.14.0
  - pip=21.1.3
  - pysam=0.16.0
  - pip:
    - numpy==1.16.4
    - scipy==1.5.4
    - opencv-python-headless==4.5.4.58
    - beautifulsoup4==4.9.3
    - intervaltree==3.1.0
    - pyvcf==0.6.8